#!/bin/sh
# Regenerates map_stmildreds_00_lib.luau from the house library + the St. Mildred's extras.
cd "$(dirname "$0")"
{
echo '-- St. Mildred'"'"'s Chapel builder library (map at Workspace.Maps.StMildreds, X offset 4500). GENERATED by map_stmildreds_mklib.sh:'
echo '-- house_00_lib.luau + house_01_props.luau (namespace _G.SMB, world offset B.O applied in B.part/B.cutter) + map_stmildreds_00x_extras.luau.'
echo '-- Rebuild order (one execute_luau each): 00_lib, 01_site, 02_masonry, 02b_windows_roofs, 03_ground, 04_tower, 05_crypt, 06_graveyard, 07_corruption; then validate, audit, pathcheck. Stage with map_stmildreds_run.sh and run _G.SMRUN() (see run.sh).'
perl -pe 's/_G\.HB/_G.SMB/g; s/^(\s*)p\.CFrame = cf$/$1p.CFrame = cf + B.O/; s/return workspace:FindFirstChild\("House"\)/local m = workspace:FindFirstChild("Maps") return m and m:FindFirstChild("StMildreds")/; s/^B\.C = \{/B.O = Vector3.new(4500, 0, 0)\nB.C = {/; s/^return "lib ok"$//' house_00_lib.luau
perl -pe 's/^local B = _G\.HB$//; s/\.CFrame = (w?b) \*/.CFrame = CFrame.new(B.O) * $1 */g; s/^return "props ok"$//' house_01_props.luau
sed 's/^return "extras ok"$/return "SMB lib ok"/' map_stmildreds_00x_extras.luau
} > map_stmildreds_00_lib.luau
echo "lib $(wc -l < map_stmildreds_00_lib.luau) lines"
